---
title: "proj3_dataviz"
author: "Honey, Sonya, James, Vuthy"
date: "Saturday, March 28, 2015"
output: html_document
---

**Use Sekhar's method to create award and category matrices**
```{r, echo=FALSE}
library(dplyr)
library(tidyr)

awards_df <- read.csv("Awards_File.csv",stringsAsFactors=F)
awards_modified <- awards_df[,c(1,3,4,6)]
head(awards_modified)
awards_modified <- awards_modified %>%
  group_by(movie_id,year,category_id) %>%
  summarise(won=max(won))
awards_re_modified <- spread((awards_modified),category_id,won)
head(awards_re_modified)
award_categories <- unique(data.frame(category_id=awards_df$category_id,category_name=awards_df$category_name))
rownames(award_categories) <- NULL
names(awards_re_modified) <- c("movie_id", "year",  "c1",  "c2",  "c3",  "c4",  "c5", "c6",  "c7",  "c8",  "c9", "c10", "c11", "c12",
                               "c13", "c14", "c15","c16", "c17", "c18", "c19", "c20", "c21", "c22", "c23")
```


**Correlation Matrix**

***Modify awards matrix to set NA = 0***
```{r, echo = TRUE}
awards_mod <- awards_re_modified #create new var to preserve original
awards_mod[is.na(awards_mod)] <- 0 #set NA = 0
```

***Correlation matrix, display circles***

```{r, echo = TRUE}

library(corrplot)
W <- cor(awards_mod[3:25]) #correlate c1:c23
corrplot(W, method = "circle")
```

***Correlation matrix, display nunbers***
```{r, echo=TRUE}
corrplot(W, method = "number")
```

***Correlation matrix, display ellipses***
```{r, echo=TRUE}
corrplot(W, method = "ellipse")
```

***Correlation matrix, display squares***
```{r, echo=TRUE}
corrplot(W, method = "square")
```

***Correlation matrix, using ggplot2
```{r, echo=TRUE}
library(ggplot2)
library(reshape2)
qplot(x=Var1, y=Var2, data=melt(cor(awards_mod[3:25])), fill=value, geom="tile")
```
