---
title: "Data Visualization"
author: "Honey, Vuthy, James, Sonya"
date: "March 24, 2015"
output: html_document
---

Data Visualization for the IS607 Project No. 2 | CUNY MSDA 

Load data
```{r}
load("Awards.Data.RData")

#View(data.awards)
```

```{r, warning=FALSE, message=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(knitr)
#library(grid)
library(gridExtra)
```


```{r, warning=FALSE, message=FALSE}
# Create BP, a dataframe showing only Best Picture Winners
BP <- filter(data.awards, category_name == "BEST PICTURE", won == 1)

# Create BP.AlsoNom, a dataframe showing what other categories the Best Picture Winners were NOMINATED for
BP.AlsoNom <- left_join(BP, data.awards, by = "movie_name") 
BP.AlsoNom <- filter(BP.AlsoNom, category_name.y != "BEST PICTURE") 
BP.AlsoNom <- select(BP.AlsoNom, category_name.y) 
BP.AlsoNom <- count(BP.AlsoNom, category_name.y)
BP.AlsoNom <- arrange(BP.AlsoNom, desc(n))

# Create BP.AlsoWon, a dataframe showing what other categories the Best Picture winners WON
data.awards.won <- filter(data.awards, won == 1)

BP.AlsoWon <- left_join(BP, data.awards.won, by = "movie_name")
BP.AlsoWon <- filter(BP.AlsoWon, category_name.y != "BEST PICTURE") 
BP.AlsoWon <- select(BP.AlsoWon, category_name.y) 
BP.AlsoWon <- count(BP.AlsoWon, category_name.y)
BP.AlsoWon <- arrange(BP.AlsoWon, desc(n))

kable(cbind(BP.AlsoNom, BP.AlsoWon), 
      col.names = c("Category Nominations", "Count", "Category Winners", "Count"))
```

#Figure 1
Answers question "Each year's best picture winner was also nominated in: Editing Category X% of the time,
Cinematography Y% of the time, Best Score Z% of the time... visualized as a bar chart in decending order
```{r}
nom <- ggplot(data = BP.AlsoNom, aes(x = reorder(category_name.y, n), y=n)) + geom_bar(stat="identity") + coord_flip() + labs(x = "Category", y = "Nominations")

win <- ggplot(data = BP.AlsoWon, aes(x = reorder(category_name.y, n), y=n)) + geom_bar(stat="identity") + coord_flip() + labs(x = "Category", y = "Wins") + ylim(0, 80)

grid.arrange(nom, win, ncol=1)
```

